In [ ]:
# Making rows using standardscaler or interpolated values

# seed random number generator
seed(1)
# generate random numbers between 0-1
new_data={}
l=[]
def random_Values(data):
  for i in range(len(data.columns)):
    #for j in range((len(df)-len(data))):
    values = np.random.uniform(min(data[data.columns[i]]),max(data[data.columns[i]]),(len(df)-len(data)))
      #l.append(values)
    new_data[data.columns[i]]=values
  return new_data

#new_data={'Year':list(df['Year'][:78]),'Aircraft Deps (000)':v, 'Aircraft KMs (mils)', 'ASKs (mils)','Cargo RTKs (mils)', 'Freight RTKs (mils)', 'Freight Tonnes (mils)','Mail RTKs (mils)', 'Pax (mils)', 'PLF', 'RPKs (mils)'}
    
new_data = pd.DataFrame(random_Values(p),columns=p.columns)

In [ ]:
## inverse tranformation to predict values of the empty rows

scaled_features = pd.concat([new_data,p])
re_scaled_features = scaler.inverse_transform(scaled_features)
re_scaled_df = pd.DataFrame(re_scaled_features, columns = col_names)
re_scaled_df

In [ ]:
import numpy as np
import pandas as pd


df = pd.DataFrame(np.c_[np.arange(6), np.random.randint(1, 3, size=6)])  # make a dataset
def createrows(df,n_copies):
  subset = df[df.iloc[:, -1] > 1]   # getting the last column as a dataframe
  # making new rows
  extra = pd.concat([subset] * n_copies).add(np.random.uniform(0, 0.05, len(subset) * n_copies), axis='rows')
  # making a new data set
  result = df.append(extra, ignore_index=True)
  return result

In [ ]:
createrows(df,3)

           0         1
0   0.000000  1.000000
1   1.000000  2.000000
2   2.000000  2.000000
3   3.000000  1.000000
4   4.000000  1.000000
5   5.000000  1.000000
6   1.010292  2.010292
7   2.033915  2.033915
8   1.046635  2.046635
9   2.013953  2.013953
10  1.028182  2.028182
11  2.012972  2.012972

In [ ]:
# filling multiple na values
df.fillna({'team':'Unknown', 'points': 0, 'assists': 'zero'}, inplace=True)

In [ ]:
# filling na values with another column values
df['Col1'].fillna(df['Col2'])

KeyError: ignored

In [ ]:
# filling na values with mean column mean
dff.fillna(dff.mean()["B":"C"])

In [ ]:
dff.mean()["B":"C"]

In [ ]:
dff = pd.DataFrame(np.random.randn(10, 3), columns=list("ABC"))

dff.iloc[3:5, 0] = np.nan

dff.iloc[4:6, 1] = np.nan

dff.iloc[5:8, 2] = np.nan
#dff.where(pd.notna(dff), dff.mean(), axis="columns")
dff.count()   ## counts without na values (column wise)

A    8
B    8
C    7
dtype: int64

In [ ]:
dff.describe()
dff.info()
dff.dtypes

In [ ]:
dff.corr()

In [ ]:
dff.nunique()

In [ ]:
#!pip install autoviz
import pandas as pd
from autoviz.AutoViz_Class import AutoViz_Class

#EDA using Autoviz
autoviz = AutoViz_Class().AutoViz('train.csv')

In [ ]:
#!pip install dtale

In [ ]:
import dtale
import pandas as pd

dtale.show(pd.read_csv("titanic.csv"))

http://75ff086e6bab:40000/dtale/main/1

In [ ]:
json_str = excel_data_df.to_json(orient='records')  # to show the data row-wise

In [ ]:
out_file = open("F:\Aakanksha\Jupyter\JSON.json", "w")
json.dump(Json, out_file, indent = 6)
out_file.close()

In [ ]:
seaborn.catplot(*, x=None, y=None, hue=None, data=None, row=None, col=None, kind=’strip’, color=None, palette=None, **kwargs)
kind = “strip”, “swarm”, “box”, “violin”, “boxen”, “point”, “bar”,“count”